version: 0.0
os: linux
files:
  - source: /main.js
    destination: /var/www/html/
hooks:
  BeforeInstall:
    - location: deploy/install_dependencies
      timeout: 300
      runas: root 
  AfterInstall:
    - location: deploy/restart_server
      timeout: 300
      runas: root
